# Generated by Django 4.2.7 on 2025-04-02 23:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('temas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_entrega', models.DateField()),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='temas.tema')),
            ],
        ),
    ]
