# Generated by Django 5.1.4 on 2025-03-10 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField()),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='unidades.unidad')),
            ],
        ),
    ]
