# Generated by Django 5.1.4 on 2025-04-23 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='porcentaje_completado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de progreso del estudiante en el curso', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
