# Generated by Django 5.1.4 on 2025-04-23 03:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0003_inscripcion_porcentaje_completado'),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='porcentaje_completado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.CreateModel(
            name='TareaCompletada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_completadas', to='inscripciones.inscripcion')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completados', to='tareas.tarea')),
            ],
            options={
                'unique_together': {('inscripcion', 'tarea')},
            },
        ),
    ]
